# ====================================================
# Cloud Build CI/CD パイプライン
#
# 初回セットアップ後のコード変更を自動デプロイします。
#
# 実行:
#   gcloud builds submit --config cloudbuild.yaml
#
# トリガー登録 (push 時に自動実行):
#   gcloud builds triggers create github \
#     --repo-name=vuln-agent --repo-owner=YOUR_ORG \
#     --branch-pattern="^main$" \
#     --build-config=cloudbuild.yaml
# ====================================================

substitutions:
  _REGION: asia-northeast1
  _AGENT_NAME: vulnerability-management-agent
  _AGENT_ENGINE_RETENTION: "1"

steps:
  # =========================================
  # Step 1: Secret Manager から .env を生成
  # =========================================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: build-env
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "[Step 1/5] Secret Manager から .env を生成します"
        cat > agent/.env <<EOF
        GMAIL_OAUTH_TOKEN=$(gcloud secrets versions access latest --secret=vuln-agent-gmail-oauth-token 2>/dev/null || echo '')
        SIDFM_SENDER_EMAIL=$(gcloud secrets versions access latest --secret=vuln-agent-sidfm-sender 2>/dev/null || echo 'noreply@sidfm.com')
        SBOM_DATA_BACKEND=$(gcloud secrets versions access latest --secret=vuln-agent-sbom-data-backend 2>/dev/null || echo 'sheets')
        SBOM_SPREADSHEET_ID=$(gcloud secrets versions access latest --secret=vuln-agent-sbom-spreadsheet-id 2>/dev/null || echo '')
        SBOM_SHEET_NAME=$(gcloud secrets versions access latest --secret=vuln-agent-sbom-sheet-name 2>/dev/null || echo 'SBOM')
        OWNER_SHEET_NAME=$(gcloud secrets versions access latest --secret=vuln-agent-owner-sheet-name 2>/dev/null || echo '担当者マッピング')
        BQ_SBOM_TABLE_ID=$(gcloud secrets versions access latest --secret=vuln-agent-bq-sbom-table-id 2>/dev/null || echo '')
        BQ_OWNER_MAPPING_TABLE_ID=$(gcloud secrets versions access latest --secret=vuln-agent-bq-owner-table-id 2>/dev/null || echo '')
        DEFAULT_CHAT_SPACE_ID=$(gcloud secrets versions access latest --secret=vuln-agent-chat-space-id 2>/dev/null || echo '')
        BQ_HISTORY_TABLE_ID=$(gcloud secrets versions access latest --secret=vuln-agent-bq-table-id 2>/dev/null || echo '')
        GCP_PROJECT_ID=${PROJECT_ID}
        GCP_LOCATION=${_REGION}
        EOF
        cat agent/.env

  # =========================================
  # Step 2: Agent Engine をデプロイ
  # =========================================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: deploy-agent
    entrypoint: bash
    args:
      - "-c"
      - |
        set -euo pipefail
        echo "[Step 2/5] Agent Engine のデプロイ準備: google-adk をインストールします"
        rm -rf /workspace/.venv-adk
        adk_bin=""
        if python3 -m venv /workspace/.venv-adk 2>/tmp/venv_err.log; then
          /workspace/.venv-adk/bin/python -m pip install -q --upgrade pip
          /workspace/.venv-adk/bin/python -m pip install -q google-adk
          adk_bin="/workspace/.venv-adk/bin/adk"
        else
          echo "venv 作成に失敗したため user site インストールにフォールバックします"
          cat /tmp/venv_err.log || true
          python3 -m pip install -q --user --break-system-packages google-adk
          adk_bin="$(python3 -m site --user-base)/bin/adk"
        fi
        if [ ! -x "$$adk_bin" ]; then
          echo "adk CLI が見つかりません: $$adk_bin"
          /workspace/.venv-adk/bin/python -m pip show google-adk 2>/dev/null || true
          python3 -m pip show google-adk 2>/dev/null || true
          exit 127
        fi
        "$$adk_bin" --version || true
        echo "[Step 2/5] Agent Engine をデプロイします"
        cd agent
        "$$adk_bin" deploy agent_engine \
          --project=${PROJECT_ID} \
          --region=${_REGION} \
          --display_name=${_AGENT_NAME} \
          --env_file=.env .

        echo "[Step 2/5] 古い Agent Engine リソースを整理します"
        retention_count="${_AGENT_ENGINE_RETENTION}"
        if ! [[ "$$retention_count" =~ ^[0-9]+$$ ]] || [ "$$retention_count" -lt 1 ]; then
          echo "_AGENT_ENGINE_RETENTION の値が不正なため 1 を使用します: $$retention_count"
          retention_count="1"
        fi

        token="$(gcloud auth print-access-token)"
        api_base="https://${_REGION}-aiplatform.googleapis.com/v1"
        engines_json="$(curl -sSf -H "Authorization: Bearer $$token" \
          "$$api_base/projects/${PROJECT_ID}/locations/${_REGION}/reasoningEngines")"

        delete_targets="$(printf '%s' "$$engines_json" | python3 -c 'import json,sys; retention=int(sys.argv[1]); display_name=sys.argv[2]; engines=json.load(sys.stdin).get("reasoningEngines", []); filtered=[e for e in engines if e.get("displayName")==display_name and e.get("name")]; filtered.sort(key=lambda e: e.get("createTime", ""), reverse=True); print("\n".join(e["name"] for e in filtered[retention:]))' "$$retention_count" "${_AGENT_NAME}")"

        preserved_engine="$(gcloud secrets versions access latest \
          --secret=vuln-agent-resource-name 2>/dev/null || echo '')"
        if [ -n "$$preserved_engine" ]; then
          delete_targets="$(printf '%s\n' "$$delete_targets" | awk -v preserve="$$preserved_engine" '$0 != preserve')"
          echo "保持対象の Agent Engine を削除対象から除外しました: $$preserved_engine"
        fi

        if [ -z "$$delete_targets" ]; then
          echo "削除対象の Agent Engine はありません。"
        else
          while IFS= read -r engine_name; do
            [ -z "$$engine_name" ] && continue
            echo "削除: $$engine_name"
            curl -sSf -X DELETE -H "Authorization: Bearer $$token" \
              "$$api_base/$$engine_name" >/dev/null || \
              echo "警告: 削除に失敗しました: $$engine_name"
          done <<< "$$delete_targets"
        fi
    waitFor:
      - build-env

  # =========================================
  # Step 3: Live Gateway を Cloud Run にデプロイ
  # =========================================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: deploy-live-gateway
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "[Step 3/5] Live Gateway デプロイ条件を確認します"
        AGENT_RESOURCE_NAME=$(gcloud secrets versions access latest \
          --secret=vuln-agent-resource-name 2>/dev/null || echo '')
        if [ -z "$$AGENT_RESOURCE_NAME" ]; then
          echo "vuln-agent-resource-name が未登録です。Live Gateway のデプロイをスキップします。"
          exit 0
        fi
        GEMINI_KEY=$(gcloud secrets versions access latest \
          --secret=vuln-agent-gemini-api-key 2>/dev/null || echo '')
        if [ -z "$$GEMINI_KEY" ]; then
          echo "vuln-agent-gemini-api-key が未登録です。Live Gateway のデプロイをスキップします。"
          exit 0
        fi
        echo "[Step 3/5] Live Gateway を Cloud Run にデプロイします"
        gcloud run deploy vuln-agent-live-gateway \
          --source=live_gateway \
          --region=${_REGION} \
          --set-env-vars="GCP_PROJECT_ID=${PROJECT_ID},GCP_LOCATION=${_REGION},AGENT_RESOURCE_NAME=$$AGENT_RESOURCE_NAME" \
          --set-secrets="GEMINI_API_KEY=vuln-agent-gemini-api-key:latest" \
          --service-account=vuln-agent-sa@${PROJECT_ID}.iam.gserviceaccount.com \
          --allow-unauthenticated \
          --memory=512Mi \
          --timeout=3600 \
          --quiet
    waitFor:
      - deploy-agent

  # =========================================
  # Step 4: Scheduler を Cloud Functions にデプロイ
  # =========================================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: deploy-scheduler
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "[Step 4/5] Scheduler デプロイ条件を確認します"
        AGENT_RESOURCE_NAME=$(gcloud secrets versions access latest \
          --secret=vuln-agent-resource-name 2>/dev/null || echo '')
        if [ -z "$$AGENT_RESOURCE_NAME" ]; then
          echo "vuln-agent-resource-name が未登録です。Scheduler のデプロイをスキップします。"
          exit 0
        fi
        echo "[Step 4/5] Scheduler を Cloud Functions にデプロイします"
        gcloud functions deploy vuln-agent-scheduler \
          --gen2 \
          --runtime=python312 \
          --region=${_REGION} \
          --source=scheduler \
          --entry-point=run_vulnerability_scan \
          --trigger-http \
          --no-allow-unauthenticated \
          --service-account=vuln-agent-sa@${PROJECT_ID}.iam.gserviceaccount.com \
          --set-env-vars="GCP_PROJECT_ID=${PROJECT_ID},GCP_LOCATION=${_REGION},AGENT_RESOURCE_NAME=$$AGENT_RESOURCE_NAME" \
          --memory=512MB \
          --timeout=540s \
          --quiet
    waitFor:
      - deploy-agent

  # =========================================
  # Step 5: Web UI を Cloud Storage にデプロイ
  # =========================================
  - name: "gcr.io/cloud-builders/gsutil"
    id: deploy-web-ui
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "[Step 5/5] Web UI を Cloud Storage にデプロイします"
        BUCKET=gs://${PROJECT_ID}-vuln-agent-ui
        gsutil mb -p ${PROJECT_ID} -l ${_REGION} $$BUCKET 2>/dev/null || true
        gsutil web set -m index.html -e index.html $$BUCKET
        gsutil -m rsync -r -d web $$BUCKET
        gsutil iam ch allUsers:objectViewer $$BUCKET
    waitFor:
      - "-"

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 2400s
